SELECT * FROM film 

CREATE  TEMPORARY TABLE  LENGHT_BUCKET_DATA AS
SELECT 
TITLE, 
DESCRIPTION, 
LENGTH, 
CASE 
WHEN length<60 then 'under 1 hour' 
WHEN length>= 60 and length < 90 then '1-1.5 HOUR' 
WHEN LENGTH>= 90 THEN 'over 1.5 hours'  
ELSE null END AS LENGHT_BUCKET  
from film 

SELECT * FROM LENGHT_BUCKET_DATA 
WHERE LENGHT_BUCKET='under 1 hour' 

SELECT *  FROM customer 
SELECT Distinct active 
FROM customer 

SELECT 
first_name, 
last_name, 
email, 
CASE 
WHEN STORE_ID=1 AND ACTIVE=1 THEN 'STORE 1 ACTIVE CUSTOMER' 
WHEN STORE_ID=1 AND ACTIVE=0 THEN 'STORE 1 INACTIVE CUSTOMER' 
WHEN STORE_ID=2 AND ACTIVE=1 THEN 'STORE 2 ACTIVE CUSTOMER' 
WHEN STORE_ID=2 AND ACTIVE=0 THEN 'STORE 2 INACTIVE CUSTOMER' 
ELSE NULL END AS remarks 
FROM customer 

SELECT * FROM inventory 

SELECT 
FILM_ID,
COUNT(CASE WHEN STORE_ID=1 THEN film_id ELSE NULL END) AS store_1_inventory, 
COUNT(CASE WHEN STORE_ID=2 THEN film_id ELSE NULL END) AS store_2_inventory,  
count(FILM_ID) as TOTAL_COPIES 
FROM INVENTORY 
GROUP BY FILM_ID  
HAVING TOTAL_COPIES>5
ORDER BY TOTAL_COPIES DESC

SELECT 
FILM_ID,
COUNT(INVENTORY_ID) 
FROM inventory  
GROUP BY  
FILM_ID 
 
 SELECT * FROM customer 
 
 SELECT  
 STORE_ID, 
 COUNT(CASE WHEN ACTIVE=1 THEN ACTIVE ELSE NULL END) AS active_customer, 
COUNT(CASE WHEN ACTIVE=0 THEN ACTIVE ELSE NULL END) AS inactive_customer, 
count(active) as total
FROM customer 
GROUP BY store_id
 

 
 




